import type { Order, Pizza } from './types'

export const MOCK_PIZZAS: Pizza[] = [
  {
    id: '1',
    title: 'Итальянский квартал',
    description: 'Томатный соус, моцарелла, пепперони, вяленые томаты и свежий базилик.',
    price: 190,
    image: '/pizza/pepperoni.png',
  },
  {
    id: '2',
    title: 'Мексиканская',
    description: 'Острый соус сальса, говядина, перец халапеньо, кукуруза и красный лук.',
    price: 125,
    image: '/pizza/vegetarian.png',
  },
  {
    id: '3',
    title: 'Тонно',
    description: 'Тунец, красный лук, каперсы, моцарелла и нежный сливочный соус.',
    price: 125,
    image: '/pizza/seafood.png',
  },
  {
    id: '4',
    title: 'Липурия',
    description: 'Четыре вида мяса, копчёная колбаса, бекон и ароматные травы.',
    price: 150,
    image: '/pizza/prosciutto.png',
  },
  {
    id: '5',
    title: 'Каприлло',
    description: 'Моцарелла, свежие томаты, руккола и капли соуса песто.',
    price: 150,
    image: '/pizza/margherita.png',
  },
  {
    id: '6',
    title: 'Тоннончипола',
    description: 'Тунец, сладкий лук, оливки и нотка лимона на тонком тесте.',
    price: 150,
    image: '/pizza/hawaiian.png',
  },
  {
    id: '7',
    title: 'Пепперони',
    description: 'Классика: двойная пепперони, моцарелла и пикантный томатный соус.',
    price: 150,
    image: '/pizza/pepperoni.png',
  },
  {
    id: '8',
    title: 'Наполи',
    description: 'Анчоусы, каперсы, орегано и настоящий неаполитанский вкус.',
    price: 150,
    image: '/pizza/margherita.png',
  },
  {
    id: '9',
    title: 'Маджоре',
    description: 'Ветчина, шампиньоны, чёрные оливки, перец и много моцареллы.',
    price: 140,
    image: '/pizza/vegetarian.png',
  },
  {
    id: '10',
    title: 'Бонне пицца',
    description: 'Курица, грибы, сливочный соус и зелень — нежный и сытный вкус.',
    price: 115,
    image: '/pizza/prosciutto.png',
  },
  {
    id: '11',
    title: 'Четыре сыра',
    description: 'Моцарелла, горгонзола, пармезан и чеддер на сливочной основе.',
    price: 140,
    image: '/pizza/quattro-formaggi.png',
  },
  {
    id: '12',
    title: 'Бьянка',
    description: 'Белая пицца без томатов: сливки, моцарелла, чеснок и розмарин.',
    price: 150,
    image: '/pizza/quattro-formaggi.png',
  },
  {
    id: '13',
    title: 'Полло',
    description: 'Куриное филе, соус барбекю, красный лук и кукуруза.',
    price: 125,
    image: '/pizza/hawaiian.png',
  },
  {
    id: '14',
    title: 'Фурнелла',
    description: 'Фирменная пицца: томаты, моцарелла, песто и вяленые помидоры.',
    price: 220,
    image: '/pizza/margherita.png',
  },
  {
    id: '15',
    title: 'Хот дог',
    description: 'Сосиски, карамелизированный лук и фирменная горчичная заливка.',
    price: 190,
    image: '/pizza/hot-dog.png',
  },
  {
    id: '16',
    title: 'Квадро Стайл',
    description: 'Ветчина, бекон, пепперони и колбаски для настоящих мясоедов.',
    price: 190,
    image: '/pizza/pepperoni.png',
  },
  {
    id: '17',
    title: 'Мона Лиза',
    description: 'Креветки, руккола, черри и лёгкий лимонно-сливочный соус.',
    price: 150,
    image: '/pizza/seafood.png',
  },
  {
    id: '18',
    title: 'Сырный Парус',
    description: 'Нежная сырная пицца с бортиком, наполненным моцареллой.',
    price: 150,
    image: '/pizza/quattro-formaggi.png',
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-1042',
    customerName: 'Андрей Попеску',
    phoneNumber: '+373 69 123 456',
    address: 'ул. Штефан чел Маре 15, кв. 32',
    items: [
      { id: '9', title: 'Маджоре', price: 140, quantity: 2 },
      { id: '15', title: 'Хот дог', price: 190, quantity: 1 },
    ],
    total: 470,
    status: 'PENDING',
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'ORD-1041',
    customerName: 'Мария Русу',
    phoneNumber: '+373 68 987 654',
    address: 'бул. Дачия 42',
    items: [{ id: '11', title: 'Четыре сыра', price: 140, quantity: 3 }],
    total: 420,
    status: 'PENDING',
    createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: 'ORD-1039',
    customerName: 'Ион Чиботару',
    phoneNumber: '+373 60 555 777',
    address: 'ул. Измаил 88, кв. 5',
    items: [
      { id: '7', title: 'Пепперони', price: 150, quantity: 1 },
      { id: '3', title: 'Тонно', price: 125, quantity: 1 },
    ],
    total: 275,
    status: 'ACCEPTED',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
]
